platform :ios, '15.0'
use_frameworks!

target 'DailyTasks' do
  # AWS Dependencies
  pod 'AWSMobileClient'
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSS3'
  
  # Networking
  pod 'Alamofire'
  
  # Image handling
  pod 'SDWebImage'
  
  # Keychain
  pod 'KeychainSwift'
  
  # Testing
  target 'DailyTasksTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
  
  # UI Testing
  target 'DailyTasksUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end 